# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: apogee
  # theme_night: dark
  # remove dark theme
  theme_night:
  font: minimal
  # S,  M  , L
  font_size: S

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'SAW Lab'
    description: 'SAW (SeekAnyWhere) Lab at National University of Defense Technology. We focus on 3D Computer Vision: planet-scale digital twins, GPS-independent UAV localization, and physics-based multimodal simulation.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
#    align: l
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: false
    highlight_active_link: true

# Site footer

footer:
  copyright:
#    notice: '© {year} Me. This work is licensed under {license}'
    notice: ''
    license:
      enable: false
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/seekanywhere/sawlab-ai.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: square
  comment:
    # provider: 'Chunhui Zhang'
    disqus:
      # shortname: 'Chunhui Zhang'
      show_count: false
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true

i_am_a_sponsor: true

